name: build & test

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2016, windows-latest]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v2
    - if: matrix.os == 'ubuntu-latest'
      name: deps
      run: sudo apt-get install libasound2-dev xorg-dev libglu1-mesa-dev
    - name: configure
      run: mkdir build && cd build && cmake -DASSETS=ON ..
    - name: build
      run: cmake --build build --config Debug
    - name: test
      run: cd build && ctest --build-config Debug --label-regex libs-core
