name: Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create-release:
    name: create a new Extempore release on GitHub
    runs-on: ubuntu-latest # or any other OS, doesn't matter
    timeout-minutes: 5
    steps:
      # to get the tag name
      - id: tag-name
        uses: olegtarasov/get-tag@v2

      - id: create-release-step
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.tag-name.outputs.tag }}
          draft:  ${{ endsWith(github.ref, '-draft') }}
          prerelease: ${{ endsWith(github.ref, '-pre') }}


  build:
    name: build & upload the zipfile to the GitHub releases page
    needs: create-release
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-latest
          - macos-latest
          - windows-2016
          - windows-latest
        include:
          - os: windows-2016
            cmake-generator: -G "Visual Studio 15 2017" -A x64
          - os: windows-latest
            cmake-generator: -G "Visual Studio 16 2019" -A x64

    steps:
      - uses: actions/checkout@v2

      - if: contains(matrix.os, 'ubuntu')
        name: deps
        run: sudo apt-get install libasound2-dev xorg-dev libglu1-mesa-dev

      - name: configure
        run: mkdir build && cd build && cmake ${{ matrix.cmake-generator }} -DPACKAGE=ON ..

      - name: build
        run: cmake --build build --config Release --target package

      - name: upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.create-release.steps.create-release-step.outputs.upload_url }}
          asset_path: "build/Extempore-package.zip"
          asset_name: Extempore-${{ jobs.create-release.steps.tag-name.outputs.tag }}-${{ matrix.os }}.zip
          asset_content_type: application/zip
